class SquadLimitsStruct
{
	string version;
	ref array<ref string> Class01 = {};
	ref array<ref string> Class02 = {};
	ref array<ref string> Class03 = {};
	ref array<ref string> Class04 = {};
	ref array<ref string> Class05 = {};
	ref array<ref string> Class06 = {};
	ref array<ref string> Class07 = {};
	ref array<ref string> Class08 = {};
	ref array<ref string> Class09 = {};
	ref array<ref string> Class10 = {};
	ref array<ref string> Class11 = {};
	ref array<ref string> Class12 = {};
	ref array<ref string> Class13 = {};
	ref array<ref string> Class14 = {};
	ref array<ref string> Class15 = {};
	ref array<ref string> Class16 = {};
	ref array<ref string> Class17 = {};
	ref array<ref string> Class18 = {};
	ref array<ref string> Class19 = {};
	ref array<ref string> Class20 = {};
	ref array<ref string> Class21 = {};
	ref array<ref string> Class22 = {};
	ref array<ref string> Class23 = {};
	ref array<ref string> Class24 = {};
	ref array<ref string> Class25 = {};
	ref array<ref string> Class26 = {};
	ref array<ref string> Class27 = {};
	ref array<ref string> Class28 = {};
	ref array<ref string> Class29 = {};
	ref array<ref string> Class30 = {};
	ref array<ref string> Class31 = {};
	ref array<ref string> Class32 = {};
		
	void BuildDefaultSLConfig()
	{
		Print("[SLC] Building default config file...");
		version = "0.7";
		Class01 = new array<ref string>();
		Class01.Insert("Loadout Name");
		Class01.Insert("limit to # (use numbers only, 0 to disable slot)");
		Class01.Insert("PlayerBohemia-IDGoesHere-ForWhitelistingThisSlot");
		Class02 = new array<ref string>();
		Class02.Insert("");
		Class02.Insert("");
		Class03 = new array<ref string>();
		Class03.Insert("");
		Class03.Insert("");
		Class04 = new array<ref string>();
		Class04.Insert("");
		Class04.Insert("");
		Class05 = new array<ref string>();
		Class05.Insert("");
		Class05.Insert("");
		Class06 = new array<ref string>();
		Class06.Insert("");
		Class06.Insert("");
		Class07 = new array<ref string>();
		Class07.Insert("");
		Class07.Insert("");
		Class08 = new array<ref string>();
		Class08.Insert("");
		Class08.Insert("");
		Class09 = new array<ref string>();
		Class09.Insert("");
		Class09.Insert("");
		Class10 = new array<ref string>();
		Class10.Insert("");
		Class10.Insert("");
		Class11 = new array<ref string>();
		Class11.Insert("");
		Class11.Insert("");
		Class12 = new array<ref string>();
		Class12.Insert("");
		Class12.Insert("");
		Class13 = new array<ref string>();
		Class13.Insert("");
		Class13.Insert("");
		Class14 = new array<ref string>();
		Class14.Insert("");
		Class14.Insert("");
		Class15 = new array<ref string>();
		Class15.Insert("");
		Class15.Insert("");
		Class16 = new array<ref string>();
		Class16.Insert("");
		Class16.Insert("");
		Class17 = new array<ref string>();
		Class17.Insert("");
		Class17.Insert("");
		Class18 = new array<ref string>();
		Class18.Insert("");
		Class18.Insert("");
		Class19 = new array<ref string>();
		Class19.Insert("");
		Class19.Insert("");
		Class20 = new array<ref string>();
		Class20.Insert("");
		Class20.Insert("");
		Class21 = new array<ref string>();
		Class21.Insert("");
		Class21.Insert("");
		Class22 = new array<ref string>();
		Class22.Insert("");
		Class22.Insert("");
		Class23 = new array<ref string>();
		Class23.Insert("");
		Class23.Insert("");
		Class24 = new array<ref string>();
		Class24.Insert("");
		Class24.Insert("");
		Class25 = new array<ref string>();
		Class25.Insert("");
		Class25.Insert("");
		Class26 = new array<ref string>();
		Class26.Insert("");
		Class26.Insert("");
		Class27 = new array<ref string>();
		Class27.Insert("");
		Class27.Insert("");
		Class28 = new array<ref string>();
		Class28.Insert("");
		Class28.Insert("");
		Class29 = new array<ref string>();
		Class29.Insert("");
		Class29.Insert("");
		Class30 = new array<ref string>();
		Class30.Insert("");
		Class30.Insert("");
		Class31 = new array<ref string>();
		Class31.Insert("");
		Class31.Insert("");
		Class32 = new array<ref string>();
		Class32.Insert("");
		Class32.Insert("");
	}
	
	void UpdateConfig()
	{
		Print("[SLC] Updating config file...");
		version = "0.7";
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class01", SCR_BaseGameMode.m_SquadLoadoutConfig.Class01);
		Class01.Insert("PlayerBohemia-IDGoesHere-ForWhitelistingThisSlot");
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class02", SCR_BaseGameMode.m_SquadLoadoutConfig.Class02);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class03", SCR_BaseGameMode.m_SquadLoadoutConfig.Class03);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class04", SCR_BaseGameMode.m_SquadLoadoutConfig.Class04);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class05", SCR_BaseGameMode.m_SquadLoadoutConfig.Class05);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class06", SCR_BaseGameMode.m_SquadLoadoutConfig.Class06);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class07", SCR_BaseGameMode.m_SquadLoadoutConfig.Class07);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class08", SCR_BaseGameMode.m_SquadLoadoutConfig.Class08);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class09", SCR_BaseGameMode.m_SquadLoadoutConfig.Class09);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class10", SCR_BaseGameMode.m_SquadLoadoutConfig.Class10);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class11", SCR_BaseGameMode.m_SquadLoadoutConfig.Class11);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class12", SCR_BaseGameMode.m_SquadLoadoutConfig.Class12);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class13", SCR_BaseGameMode.m_SquadLoadoutConfig.Class13);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class14", SCR_BaseGameMode.m_SquadLoadoutConfig.Class14);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class15", SCR_BaseGameMode.m_SquadLoadoutConfig.Class15);
		SCR_BaseGameMode.configLoadContainer.ReadValue("Class16", SCR_BaseGameMode.m_SquadLoadoutConfig.Class16);
		Class17 = new array<ref string>();
		Class17.Insert("");
		Class17.Insert("");
		Class18 = new array<ref string>();
		Class18.Insert("");
		Class18.Insert("");
		Class19 = new array<ref string>();
		Class19.Insert("");
		Class19.Insert("");
		Class20 = new array<ref string>();
		Class20.Insert("");
		Class20.Insert("");
		Class21 = new array<ref string>();
		Class21.Insert("");
		Class21.Insert("");
		Class22 = new array<ref string>();
		Class22.Insert("");
		Class22.Insert("");
		Class23 = new array<ref string>();
		Class23.Insert("");
		Class23.Insert("");
		Class24 = new array<ref string>();
		Class24.Insert("");
		Class24.Insert("");
		Class25 = new array<ref string>();
		Class25.Insert("");
		Class25.Insert("");
		Class26 = new array<ref string>();
		Class26.Insert("");
		Class26.Insert("");
		Class27 = new array<ref string>();
		Class27.Insert("");
		Class27.Insert("");
		Class28 = new array<ref string>();
		Class28.Insert("");
		Class28.Insert("");
		Class29 = new array<ref string>();
		Class29.Insert("");
		Class29.Insert("");
		Class30 = new array<ref string>();
		Class30.Insert("");
		Class30.Insert("");
		Class31 = new array<ref string>();
		Class31.Insert("");
		Class31.Insert("");
		Class32 = new array<ref string>();
		Class32.Insert("");
		Class32.Insert("");
	}
}

class PlayerIDStruct
{
	static string slc_menuPlayerId = "";
	static ref array<ref string> slc_availableLoadouts = {};
}